#!/bin/sh

REPO_DIR="$(pwd)"
REPO="${REPO_DIR##*/}"

PROJ_DIR=

case $REPO in

    "framework")
        echo ""
        echo "Running hooks for framework repository [galasa-dev/framework]"
        echo ""
        PROJ_DIR="$REPO_DIR/galasa-parent"
        ;;

    "managers")
        echo ""
        echo "Running hooks for managers repository [galasa-dev/managers]"
        echo ""
        PROJ_DIR="$REPO_DIR/galasa-managers-parent"
        ;;
    
    *)
        echo ""
        echo "UNKNOWN REPOSITORY"
        echo "This hook is only designed to be used with specific Galasa repositories"
        echo "Please make sure the repository you're using is supported and/or check the documentation."
        echo ""
        exit 1
        ;;
esac

$REPO_DIR/.git/hooks/scripts/utilities/wrapper.sh $REPO_DIR $PROJ_DIR
RET_CODE=$?

exit $RET_CODE
