#!/bin/sh

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

# git verify-commit << Should validate the GPG signature created by git commit -S
# Perhaps a significant improvement over allowing a hook to insert a message...
# Possibly needs to be placed within the "commit-msg" check rather than prepare-commit-msg << Test first before moving.

# Gets rid of "Please enter the commit message..."
/usr/bin/perl -i.bak -ne 'print unless(m/^. Please enter the commit message/..m/^#$/)' "$COMMIT_MSG_FILE"

# This adds a Signed-off-by line to the message, that can
# still be edited.  This is rarely a good idea. We need to find a better way.
SOB=$(git var GIT_COMMITTER_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
git interpret-trailers --in-place --trailer "$SOB" "$COMMIT_MSG_FILE"
if test -z "$COMMIT_SOURCE"
then
  /usr/bin/perl -i.bak -pe 'print "\n" if !$first_line++' "$COMMIT_MSG_FILE"
fi
